import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ConvexClientProvider } from "@/provider/convex-client-provider";
import { Toaster } from "@/components/ui/sonner";
import { RenameModal } from "@/components/modals/renameModal";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="inter.className">
        <ConvexClientProvider>
          <Toaster/>
          <RenameModal/>
          {children}

        </ConvexClientProvider>
      </body>
    </html>
  );
}